### PR TITLE
DontblinkV

### PR DESCRIPTION
**Pull request by Viktroryia**

### CODE REVIEW

**Review by Muzayna — APPROVED** [review]
very nice code!

**Comment by VadimPetrov23** [comment]
looks good for me

**Review by OzgurHoruz — CHANGES_REQUESTED** [review]
Please add another line

**Review by VadimPetrov23 — COMMENTED** [review]
nice

**Review by OzgurHoruz — COMMENTED** [review]
where is the other line?

**Review by ivaod — COMMENTED** [review]
Bravo!

**Review by VadimPetrov23 — COMMENTED** [review]
changes looks good

**Comment by hasanc17** [comment]
well done

**Review by hasanc17 — COMMENTED** [review]
change line 6 :)

**Pull request merged**
